# Generated by Django 3.2.16 on 2023-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('self_intro', models.TextField(blank=True)),
                ('qualification_1', models.CharField(max_length=50)),
                ('qualification_2', models.CharField(max_length=50)),
                ('qualification_3', models.CharField(max_length=50)),
                ('qualification_4', models.CharField(max_length=50)),
                ('qualification_5', models.CharField(max_length=50)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
