# Generated by Django 3.2.16 on 2023-02-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0003_rename_product_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='location',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
