# Generated by Django 3.2.16 on 2023-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0007_auto_20230208_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
