# Generated by Django 3.2.16 on 2023-02-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0008_alter_camp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='camp',
            name='price',
            field=models.IntegerField(),
        ),
    ]
