# Generated by Django 3.2.16 on 2023-02-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0009_auto_20230208_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='camp',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='camp',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
