# Generated by Django 3.2.16 on 2023-02-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0010_auto_20230208_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='date',
            new_name='camp_date',
        ),
    ]
