# Generated by Django 3.2.16 on 2023-02-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0011_rename_date_camp_camp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='camp_date',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='photo_main',
        ),
    ]
