# Generated by Django 3.2.16 on 2023-02-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0013_auto_20230208_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='description',
            new_name='enrollment_info',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='information',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='camp',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='safety_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
