# Generated by Django 3.2.16 on 2023-02-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summercamp', '0014_auto_20230208_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='price',
            new_name='fees',
        ),
    ]
