# Generated by Django 3.2.16 on 2023-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('lesson_date', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('payment_details', models.TextField(blank=True)),
                ('enrollment_info', models.TextField(blank=True)),
                ('safety_info', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('fees', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
