# Generated by Django 3.2.16 on 2023-02-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='lesson',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
