# Generated by Django 3.2.16 on 2023-02-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20230216_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='available',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='fees',
        ),
    ]
